# Generated by Django 4.1.6 on 2023-02-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='equipo',
            field=models.CharField(max_length=30, verbose_name='Nombre del equipo'),
        ),
    ]
