# Generated by Django 4.1.6 on 2023-02-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
