# Generated by Django 4.1.6 on 2023-02-07 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_familia_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='user',
        ),
    ]
