# Generated by Django 4.1.6 on 2023-02-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Username',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
