# Generated by Django 4.1.6 on 2023-02-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
